// src/constants/workoutExercises.ts
// Curated workout exercise library for the manual add-exercise flow on the
// Workout section. Defaults are sensible starting points, fully editable
// before adding. See app/(client)/workout-plan.tsx AddExerciseModal.
import type { ExerciseSide } from './warmupExercises';

export interface WorkoutExerciseDefault {
  id: string;
  name: string;
  defaultSets: number;
  defaultReps: number | null;
  defaultSide: ExerciseSide;
  defaultHoldSecs: number | null;
  defaultRestSecs: number;
}

export const WORKOUT_EXERCISES: WorkoutExerciseDefault[] = [
  { id: 'animal_balance_flamingo_stand', name: 'Animal balance - Flamingo stand', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'animal_balance_tree_pose', name: 'Animal balance - Tree pose', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'assisted_box_step_up_low_box', name: 'Assisted box step-up (low box)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'assisted_chest_press_machine_light_load', name: 'Assisted chest press machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'assisted_dip_push_up_machine_light_load', name: 'Assisted dip/push-up machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'assisted_pull_up_machine_counterweight_light', name: 'Assisted pull-up machine (counterweight, light)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'band_pull_apart', name: 'Band pull-apart', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'band_row_light_resistance_band', name: 'Band row (light resistance band)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'band_row_light_resistance_band_scapular_focus', name: 'Band row (light resistance band, scapular focus)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'battle_rope_light_waves_coach_supervised', name: 'Battle rope light waves (coach-supervised)', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'bird_dog', name: 'Bird dog', defaultSets: 2, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'bodyweight_squat', name: 'Bodyweight squat', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'bodyweight_squat_chair_assisted_if_needed', name: 'Bodyweight squat (chair-assisted if needed)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'bodyweight_squat_chair_assisted', name: 'Bodyweight squat (chair-assisted)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'bodyweight_squat_neutral_spine_cue', name: 'Bodyweight squat (neutral spine cue)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'box_step_up_low_box', name: 'Box step-up (low box)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'brisk_walking_in_place_around_home', name: 'Brisk walking in place / around home', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'brisk_walk_outdoor_moderate_pace', name: 'Brisk walk (outdoor, moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1200, defaultRestSecs: 0 },
  { id: 'cable_crunch_light_load', name: 'Cable crunch (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'cable_external_rotation', name: 'Cable external rotation', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'cable_face_pull', name: 'Cable face pull', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'cable_hip_abduction_clamshell_pattern_standing', name: 'Cable hip abduction (clamshell pattern, standing)', defaultSets: 2, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'cable_pull_through_hip_hinge_pattern', name: 'Cable pull through (hip hinge pattern)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'cable_pull_through_light_load', name: 'Cable pull through (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'cable_woodchop_light_load', name: 'Cable woodchop (light load)', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'chest_press_machine_light_load', name: 'Chest press machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'chest_press_machine_light_load_seated_back_supported', name: 'Chest press machine (light load, seated, back-supported)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'chest_press_machine_light_moderate_load', name: 'Chest press machine (light-moderate load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'chest_press_machine_very_light_load', name: 'Chest press machine (very light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'chest_supported_row_scapular_retraction_emphasis', name: 'Chest-supported row (scapular retraction emphasis)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'chin_tuck_deep_neck_flexor_activation', name: 'Chin tuck (deep neck flexor activation)', defaultSets: 2, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'cycling_outdoor_moderate_pace', name: 'Cycling (outdoor, moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1800, defaultRestSecs: 0 },
  { id: 'circuit_leg_press_cable_row_bike_sprint_1_round', name: 'Circuit: Leg press + Cable row + Bike sprint (1 round)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'circuit_leg_press_seated_row_recumbent_bike_sprint_1_round', name: 'Circuit: Leg press + Seated row + Recumbent bike sprint (1 round)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'circuit_sit_to_stand_seated_wall_push_seated_march_1_round', name: 'Circuit: Sit-to-stand + Seated wall push + Seated march (1 round)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'circuit_squat_to_chair_wall_push_up_march_1_round', name: 'Circuit: Squat to chair + Wall push-up + March (1 round)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'clamshell_hip_external_rotation', name: 'Clamshell (hip external rotation)', defaultSets: 2, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'crab_walk', name: 'Crab walk', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'dead_bug', name: 'Dead bug', defaultSets: 2, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'dance_workout_zumba', name: 'Dance workout / Zumba', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1800, defaultRestSecs: 0 },
  { id: 'doorway_pec_stretch', name: 'Doorway pec stretch', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'easy_paced_walk_light_recovery_cardio', name: 'Easy-paced walk (light recovery cardio)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'elliptical_trainer_moderate_pace', name: 'Elliptical trainer (moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 900, defaultRestSecs: 0 },
  { id: 'elliptical_trainer_easy_pace', name: 'Elliptical trainer (easy pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'face_pull_light_resistance_band', name: 'Face pull (light resistance band)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'freestyle_swimming_laps', name: 'Freestyle swimming laps', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1200, defaultRestSecs: 0 },
  { id: 'farmer_carry_neutral_pelvis_posture_emphasis', name: 'Farmer carry (neutral pelvis/posture emphasis)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'farmer_carry_upright_posture_emphasis', name: 'Farmer carry (upright posture emphasis)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'foam_roller_quads_calves_gentle_pressure', name: 'Foam roller - quads/calves (gentle pressure)', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'foam_roller_quads_hamstrings', name: 'Foam roller - quads/hamstrings', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'front_plank', name: 'Front plank', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'front_plank_posterior_tilt_cue', name: 'Front plank (posterior tilt cue)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'glute_bridge', name: 'Glute bridge', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'glute_bridge_march_alternating_leg_extension', name: 'Glute bridge march (alternating leg extension)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'goblet_squat_light_dumbbell', name: 'Goblet squat (light dumbbell)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'goblet_squat_neutral_spine_cue_light_dumbbell', name: 'Goblet squat (neutral spine cue, light dumbbell)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'hamstring_stretch_standing_or_supine', name: 'Hamstring stretch (standing or supine)', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'hiit_circuit_timed_blocks', name: 'HIIT circuit (timed blocks)', defaultSets: 5, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 60, defaultRestSecs: 30 },
  { id: 'hip_flexor_stretch', name: 'Hip flexor stretch', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'hip_flexor_stretch_on_bench_couch_stretch_variant', name: 'Hip flexor stretch on bench (couch stretch variant)', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'hip_hinge_to_chair_deadlift_pattern_drill', name: 'Hip hinge to chair (deadlift pattern drill)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'hip_thrust_barbell_or_machine_light_moderate_load', name: 'Hip thrust (barbell or machine, light-moderate load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'incline_dumbbell_press_light_load', name: 'Incline dumbbell press (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'incline_push_up_hands_on_bench_step', name: 'Incline push-up (hands on bench/step)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'jogging_outdoor_moderate_pace', name: 'Jogging (outdoor, moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1200, defaultRestSecs: 0 },
  { id: 'jump_rope_skipping_steady', name: 'Jump rope / skipping (steady)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 300, defaultRestSecs: 60 },
  { id: 'jump_rope_intervals', name: 'Jump rope intervals', defaultSets: 5, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 60, defaultRestSecs: 30 },
  { id: 'jump_squat_low_impact', name: 'Jump squat (low impact)', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'kneeling_hip_flexor_stretch_couch_stretch_variant', name: 'Kneeling hip flexor stretch (couch stretch variant)', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'landmine_press_controlled_posture_focused', name: 'Landmine press (controlled, posture-focused)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'lat_pulldown_light_load', name: 'Lat pulldown (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'lat_pulldown_light_load_seated', name: 'Lat pulldown (light load, seated)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'lat_pulldown_neutral_grip_scapular_depression_focus', name: 'Lat pulldown (neutral grip, scapular depression focus)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'lat_pulldown_machine_very_light_load', name: 'Lat pulldown machine (very light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'leg_press_machine_light_load', name: 'Leg press machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'leg_press_machine_light_load_partial_range', name: 'Leg press machine (light load, partial range)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'leg_press_machine_light_moderate_load', name: 'Leg press machine (light-moderate load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'leg_press_machine_very_light_load', name: 'Leg press machine (very light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'lying_leg_curl_machine_hamstring_isolation', name: 'Lying leg curl machine (hamstring isolation)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'medicine_ball_overhead_hold_light_ball', name: 'Medicine ball overhead hold (light ball)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'mini_hurdle_hops_low_hurdles', name: 'Mini hurdle hops (low hurdles)', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'mini_medicine_ball_chest_pass_against_wall', name: 'Mini medicine ball chest pass (against wall)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'mountain_climbers', name: 'Mountain climbers', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'pallof_press_anti_rotation_cable', name: 'Pallof press (anti-rotation, cable)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'plank_hold', name: 'Plank hold', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'plank_hold_knees_down_if_needed', name: 'Plank hold (knees down if needed)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'plank_hold_knees_down', name: 'Plank hold (knees down)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'plank_to_downward_dog_flow', name: 'Plank to downward dog flow', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'posterior_pelvic_tilt_supine_isolation_drill', name: 'Posterior pelvic tilt (supine, isolation drill)', defaultSets: 2, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'posterior_pelvic_tilt_on_bench_isolation_drill', name: 'Posterior pelvic tilt on bench (isolation drill)', defaultSets: 2, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'prone_y_t_w_raise_light_or_no_load', name: 'Prone Y-T-W raise (light or no load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'push_up_knees_or_full_per_ability', name: 'Push-up (knees or full, per ability)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'running_treadmill_moderate_pace', name: 'Running (treadmill, moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1200, defaultRestSecs: 0 },
  { id: 'running_outdoor_moderate_pace', name: 'Running (outdoor, moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 1200, defaultRestSecs: 0 },
  { id: 'rowing_machine_steady_state', name: 'Rowing machine (steady state)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'rowing_machine_moderate_pace', name: 'Rowing machine (moderate pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 900, defaultRestSecs: 0 },
  { id: 'recumbent_bike_intervals_30s_push_30s_easy', name: 'Recumbent bike intervals (30s push / 30s easy)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'recumbent_bike_or_pool_walking_very_easy_pace', name: 'Recumbent bike or pool walking (very easy pace)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'recumbent_bike_steady_state', name: 'Recumbent bike steady-state', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'reverse_lunge_bodyweight', name: 'Reverse lunge (bodyweight)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'reverse_pec_deck', name: 'Reverse pec deck', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'reverse_pec_deck_light_load', name: 'Reverse pec deck (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'romanian_deadlift_light_dumbbells', name: 'Romanian deadlift (light dumbbells)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'romanian_deadlift_light_dumbbells_hip_hinge_focus', name: 'Romanian deadlift (light dumbbells, hip hinge focus)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_band_pull_apart', name: 'Seated band pull-apart', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_band_row_light_resistance_band', name: 'Seated band row (light resistance band)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_bird_dog_arm_reach_only_low_strain', name: 'Seated bird dog (arm reach only, low strain)', defaultSets: 2, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'seated_cable_crunch_light_load', name: 'Seated cable crunch (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_cable_row_light_load', name: 'Seated cable row (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_cable_row_light_moderate_load', name: 'Seated cable row (light-moderate load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_cable_row_wide_grip_scapular_squeeze', name: 'Seated cable row (wide grip, scapular squeeze)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_cable_woodchop_light_load', name: 'Seated cable woodchop (light load)', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_calf_raise', name: 'Seated calf raise', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_calf_raise_machine_light_load', name: 'Seated calf raise machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_dead_bug_arm_leg_extension_low_strain', name: 'Seated dead bug (arm/leg extension, low strain)', defaultSets: 2, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 30 },
  { id: 'seated_glute_squeeze_hold', name: 'Seated glute squeeze hold', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'seated_hamstring_stretch', name: 'Seated hamstring stretch', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'seated_hip_flexor_stretch', name: 'Seated hip flexor stretch', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'seated_knee_raises_low_impact', name: 'Seated knee raises (low impact)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_leg_curl_machine_light_load', name: 'Seated leg curl machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_leg_extension_machine_light_load', name: 'Seated leg extension machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_march_intervals_20s_work_40s_rest', name: 'Seated march intervals (20s work / 40s rest)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'seated_plank_hold_forearms_on_bench', name: 'Seated plank hold (forearms on bench)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'seated_plank_hold_forearms_on_table_counter', name: 'Seated plank hold (forearms on table/counter)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'seated_row_machine_light_load', name: 'Seated row machine (light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_row_machine_light_moderate_load', name: 'Seated row machine (light-moderate load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_row_machine_very_light_load', name: 'Seated row machine (very light load)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'seated_spinal_twist', name: 'Seated spinal twist', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'seated_spinal_twist_gentle', name: 'Seated spinal twist (gentle)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'seated_wall_push_palms_on_wall_standing_or_seated_lean', name: 'Seated wall push (palms on wall, standing or seated lean)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'side_plank', name: 'Side plank', defaultSets: 2, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'side_plank_hip_focused', name: 'Side plank (hip-focused)', defaultSets: 2, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'side_plank_shoulder_supported', name: 'Side plank (shoulder-supported)', defaultSets: 2, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'single_leg_cable_pull_through', name: 'Single-leg cable pull through', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'single_leg_glute_bridge', name: 'Single-leg glute bridge', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'sit_to_stand_from_chair_supported_by_armrests', name: 'Sit-to-stand from chair (supported by armrests)', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'sit_to_stand_from_low_chair', name: 'Sit-to-stand from low chair', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'skater_hops_lateral_jumps', name: 'Skater hops (lateral jumps)', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'stair_climbing_machine_or_stairs', name: 'Stair climbing (machine or stairs)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'sprint_intervals_outdoors', name: 'Sprint intervals (outdoors)', defaultSets: 6, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 90 },
  { id: 'slow_easy_paced_walking_flat_surface', name: 'Slow easy-paced walking (flat surface)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'stability_ball_plank_knees_down', name: 'Stability ball plank (knees down)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'stability_ball_sit_core_hold', name: 'Stability ball sit (core hold)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'standing_band_row_light_resistance_band', name: 'Standing band row (light resistance band)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'standing_band_row_to_overhead_reach_postural_carryover_drill', name: 'Standing band row to overhead reach (postural carryover drill)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'standing_cable_row_to_overhead_reach_postural_carryover_drill', name: 'Standing cable row to overhead reach (postural carryover drill)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'standing_calf_raise', name: 'Standing calf raise', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'standing_calf_raise_machine_or_bodyweight', name: 'Standing calf raise (machine or bodyweight)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'standing_hamstring_stretch', name: 'Standing hamstring stretch', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },
  { id: 'standing_hip_hinge_drill_dowel_broomstick_cue', name: 'Standing hip hinge drill (dowel/broomstick cue)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'standing_knee_raises', name: 'Standing knee raises', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'standing_posture_drill_ribs_over_pelvis_cue_1_round', name: 'Standing posture drill (ribs-over-pelvis cue, 1 round)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'stationary_bike_easy_pace_light_recovery_cardio', name: 'Stationary bike easy pace (light recovery cardio)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'stationary_bike_intervals_30s_push_30s_easy', name: 'Stationary bike intervals (30s push / 30s easy)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'step_touch_intervals_30s_work_30s_rest', name: 'Step-touch intervals (30s work / 30s rest)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'step_up_low_box_step', name: 'Step-up (low box/step)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'superman_hold', name: 'Superman hold', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'supported_reverse_lunge_hand_on_wall_chair_small_range', name: 'Supported reverse lunge (hand on wall/chair, small range)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'trap_bar_deadlift_light_load_hip_hinge_integration', name: 'Trap bar deadlift (light load, hip hinge integration)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'treadmill_steady_state_walk_incline_walk', name: 'Treadmill steady-state walk/incline walk', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'very_easy_paced_walk_flat_surface_no_incline', name: 'Very easy-paced walk (flat surface, no incline)', defaultSets: 1, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 600, defaultRestSecs: 0 },
  { id: 'walking_lunge_bodyweight', name: 'Walking lunge (bodyweight)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'walking_lunge_neutral_pelvis_emphasis', name: 'Walking lunge (neutral pelvis emphasis)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'walking_posture_drill_chin_tucked_shoulders_back_1_round', name: 'Walking posture drill (chin tucked, shoulders back, 1 round)', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'wall_push_up', name: 'Wall push-up', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'wall_push_up_plus_scapular_protraction_emphasis', name: 'Wall push-up plus (scapular protraction emphasis)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'wall_sit', name: 'Wall sit', defaultSets: 2, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 20, defaultRestSecs: 30 },
  { id: 'wall_slide_scapular_retraction', name: 'Wall slide (scapular retraction)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'wall_supported_incline_push_standing_lean', name: 'Wall-supported incline push (standing lean)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'wall_supported_mini_squat_partial_range', name: 'Wall-supported mini squat (partial range)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'yoga_wheel_foam_roller_thoracic_extension', name: 'Yoga wheel / foam roller thoracic extension', defaultSets: 1, defaultReps: null, defaultSide: 'right', defaultHoldSecs: 25, defaultRestSecs: 10 },

  // ── Barbell ────────────────────────────────────────────────────────────────
  { id: 'barbell_back_squat', name: 'Barbell back squat', defaultSets: 4, defaultReps: 8, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 90 },
  { id: 'barbell_bench_press', name: 'Barbell bench press', defaultSets: 4, defaultReps: 8, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 90 },
  { id: 'barbell_deadlift', name: 'Barbell deadlift', defaultSets: 3, defaultReps: 6, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 120 },
  { id: 'barbell_overhead_press', name: 'Barbell overhead press', defaultSets: 3, defaultReps: 8, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 90 },
  { id: 'barbell_bent_over_row', name: 'Barbell bent-over row', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'barbell_romanian_deadlift', name: 'Barbell Romanian deadlift', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'barbell_hip_thrust', name: 'Barbell hip thrust', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'barbell_bicep_curl', name: 'Barbell bicep curl', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'barbell_skull_crusher_tricep', name: 'Barbell skull crusher (tricep)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },

  // ── Kettlebell ─────────────────────────────────────────────────────────────
  { id: 'kettlebell_swing', name: 'Kettlebell swing', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'kettlebell_goblet_squat', name: 'Kettlebell goblet squat', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'kettlebell_deadlift', name: 'Kettlebell deadlift', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'kettlebell_clean_and_press', name: 'Kettlebell clean and press', defaultSets: 3, defaultReps: 8, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'kettlebell_turkish_get_up', name: 'Kettlebell Turkish get-up', defaultSets: 2, defaultReps: 5, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 90 },
  { id: 'kettlebell_single_arm_row', name: 'Kettlebell single-arm row', defaultSets: 3, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'kettlebell_overhead_press', name: 'Kettlebell overhead press', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'kettlebell_front_rack_lunge', name: 'Kettlebell front-rack lunge', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 60 },

  // ── Suspension Band (TRX) ──────────────────────────────────────────────────
  { id: 'suspension_band_row_trx', name: 'Suspension band row (TRX)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'suspension_band_chest_press_trx', name: 'Suspension band chest press (TRX)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'suspension_band_squat_trx', name: 'Suspension band squat (TRX)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'suspension_band_lunge_trx', name: 'Suspension band lunge (TRX)', defaultSets: 3, defaultReps: 10, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'suspension_band_plank_trx', name: 'Suspension band plank (TRX)', defaultSets: 3, defaultReps: null, defaultSide: 'na', defaultHoldSecs: 30, defaultRestSecs: 30 },
  { id: 'suspension_band_bicep_curl_trx', name: 'Suspension band bicep curl (TRX)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'suspension_band_tricep_extension_trx', name: 'Suspension band tricep extension (TRX)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'suspension_band_hamstring_curl_trx', name: 'Suspension band hamstring curl (TRX)', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },

  // ── Dumbbell (key lifts not yet covered) ──────────────────────────────────
  { id: 'dumbbell_bench_press', name: 'Dumbbell bench press', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'dumbbell_shoulder_press', name: 'Dumbbell shoulder press', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'dumbbell_bicep_curl', name: 'Dumbbell bicep curl', defaultSets: 3, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'dumbbell_tricep_kickback', name: 'Dumbbell tricep kickback', defaultSets: 3, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'dumbbell_romanian_deadlift', name: 'Dumbbell Romanian deadlift', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 60 },
  { id: 'dumbbell_lateral_raise', name: 'Dumbbell lateral raise', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'dumbbell_chest_fly', name: 'Dumbbell chest fly', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'dumbbell_goblet_squat', name: 'Dumbbell goblet squat', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },

  // ── Triceps (bodyweight/cable) ─────────────────────────────────────────────
  { id: 'tricep_dip_bench', name: 'Tricep dip (bench)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'close_grip_push_up_tricep', name: 'Close-grip push-up (tricep focus)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'cable_tricep_pushdown', name: 'Cable tricep pushdown', defaultSets: 3, defaultReps: 15, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'overhead_tricep_extension_cable', name: 'Overhead tricep extension (cable)', defaultSets: 3, defaultReps: 12, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },

  // ── Hamstrings (dedicated) ─────────────────────────────────────────────────
  { id: 'nordic_hamstring_curl', name: 'Nordic hamstring curl', defaultSets: 3, defaultReps: 6, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 90 },
  { id: 'single_leg_hamstring_curl_cable', name: 'Single-leg hamstring curl (cable)', defaultSets: 3, defaultReps: 12, defaultSide: 'right', defaultHoldSecs: null, defaultRestSecs: 45 },
  { id: 'stability_ball_hamstring_curl', name: 'Stability ball hamstring curl', defaultSets: 3, defaultReps: 10, defaultSide: 'na', defaultHoldSecs: null, defaultRestSecs: 45 },
];
